### ISSUE TITLE
the figure generated by tauRAMD.py is not correct

### ISSUE THREAD

**Issue by autodataming** [HITS-MCM/tauRAMD#2]
I have 10 replicas.

(]$ **cat times_1.dat** 
Replica10/Replica10_ramd.log:==== RAMD ==== GROMACS will be stopped after 609950 steps.
Replica1/Replica1_ramd.log:==== RAMD ==== GROMACS will be stopped after 141200 steps.
Replica2/Replica2_ramd.log:==== RAMD ==== GROMACS will be stopped after 297250 steps.
Replica3/Replica3_ramd.log:==== RAMD ==== GROMACS will be stopped after 110800 steps.
Replica4/Replica4_ramd.log:==== RAMD ==== GROMACS will be stopped after 144100 steps.
Replica5/Replica5_ramd.log:==== RAMD ==== GROMACS will be stopped after 111700 steps.
Replica6/Replica6_ramd.log:==== RAMD ==== GROMACS will be stopped after 528550 steps.
Replica7/Replica7_ramd.log:==== RAMD ==== GROMACS will be stopped after 408600 steps.
Replica8/Replica8_ramd.log:==== RAMD ==== GROMACS will be stopped after 157150 steps.
Replica9/Replica9_ramd.log:==== RAMD ==== GROMACS will be stopped after 273650 steps.

**python tauRAMD.py  times_1.dat** 
Data found: times_1.dat
************ Dissociation times for times_1.dat ****************
[1.2199 0.2824 0.5945 0.2216 0.2882 0.2234 1.0571 0.8172 0.3143 0.5473]

 ==============   Bootstrapping and computation of tau for each replica==================

[ 1.2199  0.2824  0.5945  0.2216  0.2882  0.2234  1.0571  0.8172  0.3143
  0.5473 55.     55.     55.     55.     55.    ]
 Relative res. time and SD:  0.83 0.17 KS test: 0.33
-----------------------------------------------------------------
Residence times for 1 replicas, mean: 0.8  std: 0.0
![res_times](https://github.com/user-attachments/assets/7763fb6e-552f-4f4d-ae0b-b188eec78408)
![res_times_summary](https://github.com/user-attachments/assets/13d8e37e-d14f-4237-bd41-e4b1acba79c3)
just only 1 replica on the figure.

Could you give me some suggestions? Thank you!

**Comment by autodataming** [comment]
If you need more information about the quesiton, please tell me.

**Comment by AegithalosCaudatus** [comment]
Hi, I think the line 110 is giving problems here: "for ti in range(len(times),15): times = np.(concatenate((times, [55.0]))". Try commenting it out. Without it, I am getting the correct plots.

**Comment by DerHerbe** [comment]
Hey,
this behaviour is expected in your case. You provided a .dat file with 10 trajectories in total (in your case one trajectory per replica). Usually, based on the last snapshot of the first equilibration in Gromacs you would create replicas (for example 5) after the second equilibration step in gromacs. This snapshot is then used to create a number of trajectories (for example 10 per replica).  This would generate 5 x 10 = 50 trajectories. 

After successfully running tauRAMD you would then extract "GROMACS will be stopped" from the outputfiles of each trajectory for each replica and save the respective simulation times seperately for each replica in a file. This means that you would then get 5 files (5 replicas) with 10 trajectories each.

In this screenshot for example you have the syntax TRJ-X-Y where X represents a specific replica and Y a specific trajectory.
So this file represents all 15 trajectoris of replica one. If you now have 5 replicas you would then get 5 different files with 15 trajectories each.

![Screenshot from 2024-10-08 10-12-45](https://github.com/user-attachments/assets/c7299a6b-59e9-47fd-a86d-185f9234dead)

The bootstrapping is then performed for each file resulting in one representative residence time for each replica. Since you only provided one file with ten trajectories, you will only get one residence time out of that. Therefore you need to create X replicas with Y trajectories to create one file for each replica.

Then the tau.py script would find all replica files like so to calculate the residence time for each replica file:
![Screenshot from 2024-10-08 10-19-40](https://github.com/user-attachments/assets/29333a16-4e6e-4902-87c8-83e759544fa1)

Hope this helps.

**Comment by autodataming** [comment]
Thank you for your reply.  I use the following command to build a similar data structure.

```sh
cd Replica1
mkdir TRJ-1-1
mv *  TRJ-1-1/
cp TRJ-1-1/ TRJ-1-2/ -fr
cp TRJ-1-1/ TRJ-1-3/ -fr
cp TRJ-1-1/ TRJ-1-4/ -fr
cp TRJ-1-1/ TRJ-1-5/ -fr
cp TRJ-1-1/ TRJ-1-6/ -fr
grep "GROMACS will be stopped after" Rep*/Rep*.log > times1_.dat


cd Replica2
mkdir TRJ-2-1
mv *  TRJ-2-1/
cp TRJ-1-1/ TRJ-2-2/ -fr
cp TRJ-1-1/ TRJ-2-3/ -fr
cp TRJ-1-1/ TRJ-2-4/ -fr
cp TRJ-1-1/ TRJ-2-5/ -fr
cp TRJ-1-1/ TRJ-2-6/ -fr
grep "GROMACS will be stopped after" Rep*/Rep*.log > times2_.dat
```

then  I run the python script, it generate the new problem.



(base) []$ **python tauRAMD.py Replica1/times_1.dat Replica2/times_2.dat** 
Data found: Replica1/times_1.dat
Data found: Replica2/times_2.dat
************ Dissociation times for Replica1/times_1.dat ****************
[0.2824 0.2824 0.2824 0.2824 0.2824 0.2824]
************ Dissociation times for Replica2/times_2.dat ****************
[0.5945 0.5945 0.5945 0.5945 0.5945 0.5945]

 ==============   Bootstrapping and computation of tau for each replica==================

/usr/local/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/anaconda3/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/anaconda3/lib/python3.11/site-packages/numpy/core/_methods.py:206: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/anaconda3/lib/python3.11/site-packages/numpy/core/_methods.py:163: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/usr/local/anaconda3/lib/python3.11/site-packages/numpy/core/_methods.py:198: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
Residence times for 2 replicas, mean: nan  std: nan

**Comment by AegithalosCaudatus** [comment]
I am not sure why all your residence times are the same value, that might cause an issue during the statistics and plotting stage.

**Comment by autodataming** [comment]
> I am not sure why all your residence times are the same value, that might cause an issue during the statistics and plotting stage.

I updated the trajectory, but it still generated the same error.
@AegithalosCaudatus  @DerHerbe 
Could you give me some suggestions?
if you need more information, please tell me

```
(gmxramd2024) []$ cat times_1.dat
TRJ-1-1/Replica1_ramd.log:==== RAMD ==== GROMACS will be stopped after 219300 steps.
TRJ-1-2/Replica1_ramd.log:==== RAMD ==== GROMACS will be stopped after 635900 steps.
TRJ-1-3/Replica1_ramd.log:==== RAMD ==== GROMACS will be stopped after 154800 steps.
TRJ-1-4/Replica1_ramd.log:==== RAMD ==== GROMACS will be stopped after 101300 steps.
TRJ-1-5/Replica1_ramd.log:==== RAMD ==== GROMACS will be stopped after 116050 steps.
TRJ-1-6/Replica1_ramd.log:==== RAMD ==== GROMACS will be stopped after 1903850 steps.

(gmxramd2024) []$ python tauRAMD.py times_1.dat
Data found: times_1.dat
************ Dissociation times for times_1.dat ****************
[0.4386 1.2718 0.3096 0.2026 0.2321 3.8077]

 ==============   Bootstrapping and computation of tau for each replica==================

/opt/anaconda3/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/opt/anaconda3/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/opt/anaconda3/lib/python3.12/site-packages/numpy/core/_methods.py:206: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/opt/anaconda3/lib/python3.12/site-packages/numpy/core/_methods.py:163: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/opt/anaconda3/lib/python3.12/site-packages/numpy/core/_methods.py:198: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
Residence times for 1 replicas, mean: nan  std: nan
```

**Comment by autodataming** [comment]
I add trajectories, it success. Thank you all.

```
Data found: Replica1/times_1.dat
Data found: Replica2/times_2.dat
[219300, 635900, 154800, 101300, 116050, 1903850, 635900, 472800, 635900]
************ Dissociation times for Replica1/times_1.dat ****************
[0.4386 1.2718 0.3096 0.2026 0.2321 3.8077 1.2718 0.9456 1.2718]
[344150, 542350, 172100, 264800, 163850, 114400, 297250, 77350, 233100, 67200, 539700, 376450, 976050, 413500, 145900]
************ Dissociation times for Replica2/times_2.dat ****************
[0.6883 1.0847 0.3442 0.5296 0.3277 0.2288 0.5945 0.1547 0.4662 0.1344
 1.0794 0.7529 1.9521 0.827  0.2918]

 ==============   Bootstrapping and computation of tau for each replica==================

[ 0.4386  1.2718  0.3096  0.2026  0.2321  3.8077  1.2718  0.9456  1.2718
 55.     55.     55.     55.     55.     55.    ]
 Relative res. time and SD:  6.85 10.54 KS test: 0.4
-----------------------------------------------------------------
[0.6883 1.0847 0.3442 0.5296 0.3277 0.2288 0.5945 0.1547 0.4662 0.1344
 1.0794 0.7529 1.9521 0.827  0.2918]
 Relative res. time and SD:  0.53 0.07 KS test: 0.11
-----------------------------------------------------------------
Residence times for 2 replicas, mean: 3.65  std: 3.15

```

**Comment by DerHerbe** [comment]
Hey, 
in order to reduce the standard deviation you should definitely increase the number of trajectories per replica.

**Comment by autodataming** [comment]
> Hey, in order to reduce the standard deviation you should definitely increase the number of trajectories per replica.

Thanks for your suggestions.
